apiVersion: apps/v1
kind: Deployment
metadata:
  name: key-server
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: key-server
  template:
    metadata:
      labels:
        app: key-server
    spec:
      containers:
        - name: key-server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          command: ["/app/key-server"]  # Specify the correct executable path
          args:
            - "--max-size={{ .Values.maxSize }}"
            - "--srv-port={{ .Values.srvPort }}"
          livenessProbe:
            httpGet:
              path: /key/1024
              port: {{ .Values.service.port }}
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /metrics
              port: {{ .Values.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}